version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"

  user-profile-service:
    build: ./user-service
    ports:
      - "3002:3002"

  event-service:
    build: ./event-service
    ports:
      - "3000:3000"

  product-service:
    build: ./product-service
    ports:
      - "3005:3005"

  abonnement-service:  
    build: ./abonnement-service
    ports:
      - "3004:3004"

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
